---
deployment:
  tasks:
    - export DEPLOYPATH=/home/izmizkdb/public_html/api.valortracker.xyz
    - export REPOPATH=/home/izmizkdb/repositories/valortracker-api
    - /bin/cp -R public/build $DEPLOYPATH
    - /bin/cp -R public/images $DEPLOYPATH
